@extends('layouts.app')

@section('title', __('navs.general.home') . ' | ' . app_name())

@section('content')

醫療機構,醫院網址<br>
全生醫院,http://chuansheng.com.tw/<br>
蕭志文醫院,http://czwhp.com/<br>
國立成功大學醫學院附設醫院斗六分院,http://d6www.hosp.ncku.edu.tw/<br>
佛教慈濟醫療財團法人大林慈濟醫院,http://dalin.tzuchi.com.tw/<br>
天主教耕莘醫療財團法人耕莘醫院,http://eng.cth.org.tw/<br>
吉田耳鼻喉科醫院,http://go-gen.com/<br>
杏和醫院,http://hhh.smh.org.tw/<br>
宏恩醫院,http://hong-en.com.tw/<br>
國泰綜合醫院新竹分院,http://hsinchu.cgh.org.tw/<br>
佛教慈濟綜合醫院關山分院,http://kuanshan.tzuchi.com.tw/<br>
三重宏仁醫院,http://mail.hrh.com.tw/<br>
民族婦產科家醫科醫院,http://mthospital.com.tw/<br>
南投基督教醫院,http://ny.cch.org.tw/<br>
周宗盛醫院,http://obsgynchou.com.tw/<br>
杏豐醫院,http://singfong.com/<br>
新昆明醫院,http://skmhosp.webnode.tw/<br>
宋俊宏婦幼醫院,http://soonghospital.com.tw/<br>
佛教慈濟醫療財團法人臺中慈濟醫院,http://taichung.tzuchi.com.tw/<br>
馬偕紀念醫院臺東分院,http://ttw3.mmh.org.tw/<br>
文化醫院,http://twhospital.org/<br>
臺灣礦工醫院,http://twmgh.com/<br>
安生醫院,http://www.安生.tw/<br>
安和醫療社團法人安和醫院,http://www.ah-hosp.com.tw/<br>
聯安醫院,http://www.anhsp.com.tw/<br>
彰化基督教醫療財團法人員林基督教醫院,http://www.bc.cch.org.tw/<br>
菩提醫院,http://www.bodhi.com.tw/<br>
廣川醫院,http://www.broadriverhospital.com/<br>
志誠醫院,http://www.c-c-chen.com.tw/<br>
承安醫院,http://www.camis.com.tw/<br>
澄清醫院,http://www.ccgh.com.tw/<br>
彰化基督教醫療財團法人彰化基督教醫院,http://www.cch.org.tw/<br>
奇美醫院,http://www.chimei.org.tw/<br>
鄭婦產科診所,http://www.chjspl.com.tw/<br>
中英醫院,http://www.choninn.com.tw/<br>
重光醫院,http://www.chorng-guang.url.tw/<br>
重仁骨科醫院,http://www.chung-jen.com.tw/<br>
國立臺灣大學醫學院附設醫院竹東分院,http://www.chut.ntuh.gov.tw/<br>
中國醫藥大學新竹附設醫院,http://www.cmu-hch.cmu.edu.tw/<br>
中國醫藥大學附設醫院,http://www.cmuh.cmu.edu.tw/<br>
宏恩醫療財團法人宏恩綜合醫院,http://www.country.org.tw/<br>
三重中興醫院,http://www.cs-hospital.org.tw/<br>
中山醫院,http://www.csh.com.tw/<br>
中山醫學大學附設醫院,http://www.csh.org.tw/<br>
竹山秀傳醫院,http://www.csshow.org.tw/<br>
佳欣婦幼醫院,http://www.cswch.com.tw/<br>
建生診所,http://www.cv5555366.com.tw/<br>
戴德森醫療財團法人嘉義基督教醫院,http://www.cych.org.tw/<br>
慶昇醫院,http://www.cycsh.org.tw/<br>
大千綜合醫院,http://www.dachien.com.tw/<br>
大川醫院,http://www.dachuan.com.tw/<br>
大順醫院,http://www.dashuen.com.tw/<br>
德仁醫院,http://www.dazan.tw/<br>
達明眼科醫院,http://www.derminghosp.com.tw/<br>
第一醫院,http://www.di-yi.com.tw/<br>
戴浚銘婦兒醫院,http://www.dvdh.com.tw/<br>
敏盛綜合醫院,http://www.e-ms.com.tw/<br>
彰化基督教醫療財團法人二林基督教醫院,http://www.erhlin.cch.org.tw/<br>
天主教福安醫院,http://www.fah.org.tw/<br>
東勢鎮農會附設農民醫院,http://www.fh.org.tw/<br>
永和復康醫院,http://www.fuconhosp.com.tw/<br>
輔英科技大學附設醫院,http://www.fy.org.tw/<br>
漢銘醫院,http://www.hanming.com.tw/<br>
樂生婦幼醫院,http://www.happybirth.com.tw/<br>
馬偕紀念醫院新竹分院,http://www.hc.mmh.org.tw/<br>
恆基醫療財團法人恆春基督教醫院,http://www.hcch.org.tw/<br>
惠來醫療社團法人宏仁醫院,http://www.hongren.com.tw/<br>
弘大醫院,http://www.hopedoctors.com.tw/<br>
國立成功大學醫學院附設醫院,http://www.hosp.ncku.edu.tw/<br>
屏東民眾醫院,http://www.hospital-ez.com.tw/<br>
洪外科醫院,http://www.hsh.tw/<br>
蕭中正醫院,http://www.hsiaohospital.org/<br>
洪宗鄰醫院,http://www.htlh.com.tw/<br>
宏其婦幼醫院,http://www.hungchihospital.org.tw/<br>
洪揚醫院,http://www.hygh.com.tw/<br>
仁愛醫療財團法人台中仁愛醫院,http://www.jah.org.tw/<br>
宜蘭仁愛醫療財團法人宜蘭仁愛醫院,http://www.jen-ai.org.tw/<br>
仁村醫院,http://www.jen-chun.com.tw/<br>
大眾醫院,http://www.jiahuo.com.tw/<br>
健仁醫院,http://www.jiannren.org.tw/<br>
景美醫院,http://www.jmh.com.tw/<br>
天主教聖功醫院,http://www.joseph.org.tw/<br>
郭綜合醫院,http://www.kgh.com.tw/<br>
基隆市立醫院,http://www.kmh.gov.tw/<br>
高雄市立大同醫院,http://www.kmtth.org.tw/<br>
高雄市立聯合醫院,http://www.kmuh.gov.tw/<br>
財團法人私立高雄醫學大學附設中和紀念醫院,http://www.kmuh.org.tw/<br>
康寧醫院,http://www.knh.org.tw/<br>
光田醫療社團法人光田綜合醫院,http://www.ktgh.com.tw/<br>
李綜合醫療社團法人李綜合醫院,http://www.leehospital.com.tw/<br>
林新醫療社團法人林新醫院,http://www.lshosp.com.tw/<br>
天主教仁慈醫療財團法人仁慈醫院,http://www.mercy.org.tw/<br>
茂隆骨科醫院,http://www.mlbone.com.tw/<br>
馬偕紀念醫院,http://www.mmh.org.tw/<br>
南門綜合醫院,http://www.nanmen.com.tw/<br>
仁康醫院,http://www.njkh.com.tw/<br>
國立臺灣大學醫學院附設醫院,http://www.ntuh.gov.tw/<br>
板新醫院,http://www.panshin.com.tw/<br>
板英醫院,http://www.panying.com.tw/<br>
寶建醫療社團法人寶建醫院,http://www.paochien.com.tw/<br>
天主教惠民醫院,http://www.penhu.net/9271750/<br>
財團法人羅許基金會羅東博愛醫院,http://www.pohai.org.tw/<br>
柏仁醫院,http://www.pojen.com.tw/<br>
博仁綜合醫院,http://www.pojengh.com.tw/<br>
屏基醫療財團法人屏東基督教醫院,http://www.ptch.org.tw/<br>
宜蘭員山醫院,http://www.pumen.org.tw/<br>
仁愛醫院,http://www.rah.com.tw/<br>
彰化基督教醫療財團法人鹿港基督教醫院,http://www.rc.cch.org.tw/<br>
順安醫院,http://www.sanannh.com.tw/<br>
勝美醫院,http://www.sheng-mei.com.tw/<br>
尹書田紀念醫院,http://www.shutien.org.tw/<br>
台灣基督長老教會新樓醫療財團法人麻豆新樓醫院,http://www.sinlau.org.tw/<br>
台灣省私立桃園仁愛之家附設新生醫院,http://www.sinsheng.com.tw/<br>
新光吳火獅紀念醫院,http://www.skh.org.tw/<br>
新國民醫院,http://www.skmh.com.tw/<br>
童綜合醫療社團法人童綜合醫院,http://www.sltung.com.tw/<br>
財團法人天主教靈醫會羅東聖母醫院,http://www.smh.org.tw/<br>
新仁醫院,http://www.srh.com.tw/<br>
天主教若瑟醫療財團法人若瑟醫院,http://www.stjoho.org.tw/<br>
天主教中華聖母修女會醫療財團法人天主教聖馬爾定醫院,http://www.stm.org.tw/<br>
三重祐民綜合醫院,http://www.symh.com.tw/<br>
基督復臨安息日會醫療財團法人臺安醫院,http://www.tahsda.org.tw/<br>
臺安醫院,http://www.tai-an.com.tw/<br>
大明醫院,http://www.taminga.com.tw/<br>
桃新醫院,http://www.taoshin.com.tw/<br>
天成醫院,http://www.tcmg.com.tw/<br>
曾漢棋綜合醫院,http://www.thc-hospital.com.tw/<br>
財團法人台灣省私立台北仁濟院附設仁濟醫院,http://www.tjci-sj.org.tw/<br>
安心醫院,http://www.tjh.com.tw/<br>
仁愛醫療社團法人仁愛醫院,http://www.tnjenaihos.org.tw/<br>
通霄光田醫院,http://www.ts.ktgh.com.tw/<br>
三軍總醫院,http://www.tsgh.ndmctsgh.edu.tw/<br>
安泰醫療社團法人安泰醫院,http://www.tsmh.com.tw/<br>
慈祐醫院,http://www.tyh.org.tw/<br>
華揚醫院,http://www.tyhs.com.tw/<br>
臺北榮民總醫院桃園分院,http://www.tyvh.gov.tw/<br>
佛教慈濟醫療財團法人花蓮慈濟醫院,http://www.tzuchi.com.tw/<br>
臺中榮民總醫院,http://www.vghtc.gov.tw/<br>
臺北榮民總醫院新竹分院,http://www.vhct.gov.tw/<br>
高雄榮民總醫院屏東分院,http://www.vhlc.gov.tw/<br>
臺北榮民總醫院花東分院,http://www.vhtt.gov.tw/<br>
財團法人為恭紀念醫院,http://www.weigong.org.tw/<br>
西園醫院,http://www.westgarden.com.tw/<br>
林新醫療社團法人烏日林新醫院,http://www.wlshosp.org.tw/<br>
平鎮陽明醫院,http://www.yangminpj.com.tw/<br>
盧亞人醫院,http://www.yaren.com.tw/<br>
永川醫院,http://www.ychospital.org/<br>
怡仁綜合醫院,http://www.yeezen.com.tw/<br>
怡和醫院,http://www.yiher.com.tw/<br>
彰化基督教醫院雲林分院,http://www.yl.cch.org.tw/<br>
嘉義陽明醫院,http://www.ymhospital.com.tw/<br>
元復醫院,http://www.youngforehospital.com/<br>
祐民醫院,http://www.yowmin.com.tw/<br>
員生醫院,http://www.ysh.org.tw/<br>
阮綜合醫療社團法人阮綜合醫院,http://www.yuanhosp.com.tw/<br>
員榮醫療社團法人員榮醫院,http://www.yuanrung.com.tw/<br>
佑民醫療社團法人佑民醫院,http://www.yumin.com.tw/<br>
中國醫藥大學北港附設醫院,http://www2.bh.cmu.edu.tw/<br>
佛教慈濟綜合醫院玉里分院,http://yuli.tzuchi.com.tw/<br>
優生婦產科醫院,http://yusheng-hospital.com.tw/<br>
國軍高雄總醫院,https://802.mnd.gov.tw/<br>
國軍台中總醫院,https://803.mnd.gov.tw/<br>
國軍花蓮總醫院,https://805.mnd.gov.tw/<br>
三軍總醫院澎湖分院,https://afph.tsgh.ndmctsgh.edu.tw/<br>
義大醫療財團法人義大癌治療醫院,https://edc.edah.org.tw/<br>
義大醫療財團法人義大大昌醫院,https://edd.edah.org.tw/<br>
高雄市立民生醫院,https://kmsh.kcg.gov.tw/<br>
高雄市立凱旋醫院,https://ksph.kcg.gov.tw/<br>
衛生福利部桃園醫院新屋院區,https://sw.tygh.mohw.gov.tw/<br>
泰安醫院,https://taian.rghealth.com.tw/<br>
東元綜合醫院,https://w3.tyh.com.tw/<br>
萬華醫院,https://wanhua.rghealth.com.tw/<br>
秀傳醫療財團法人彰濱秀傳紀念醫院,https://www.cbshow.org.tw/<br>
衛生福利部胸腔病院,https://www.ccd.mohw.gov.tw/<br>
彰化基督教醫院,https://www.cch.org.tw/<br>
國泰綜合醫院,https://www.cgh.org.tw/<br>
長庚醫療財團法人醫院,https://www.cgmh.org.tw/<br>
永和振興醫院,https://www.chgh.org.tw/<br>
衛生福利部彰化醫院,https://www.chhw.mohw.gov.tw/<br>
衛生福利部嘉義醫院,https://www.chyi.mohw.gov.tw/<br>
義大醫療財團法人義大醫院,https://www.edah.org.tw/<br>
亞東紀念醫院,https://www.femh.org.tw/<br>
衛生福利部豐原醫院,https://www.fyh.mohw.gov.tw/<br>
國立臺灣大學醫學院附設醫院新竹分院,https://www.hch.gov.tw/<br>
衛生福利部花蓮醫院,https://www.hwln.mohw.gov.tw/<br>
陳仁德醫院,https://www.jdhc.org.tw/<br>
衛生福利部金門醫院,https://www.kmhp.mohw.gov.tw/<br>
臺灣基督教門諾會醫療財團法人門諾醫院,https://www.mch.org.tw/<br>
衛生福利部苗栗醫院,https://www.mil.mohw.gov.tw/<br>
衛生福利部南投醫院及其中興院區,https://www.nant.mohw.gov.tw/<br>
埔里基督教醫院,https://www.pch.org.tw/<br>
衛生福利部澎湖醫院,https://www.pngh.mohw.gov.tw/<br>
衛生福利部屏東醫院,https://www.pntn.mohw.gov.tw/<br>
臺北榮民總醫院蘇澳分院,https://www.savh.gov.tw/<br>
秀傳醫療社團法人秀傳紀念醫院,https://www.scmh.org.tw/<br>
馨蕙馨醫院,https://www.shs-h.com.tw/<br>
聖保祿修女會醫院,https://www.sph.org.tw/<br>
衛生福利部新營醫院,https://www.syh.mohw.gov.tw/<br>
衛生福利部臺中醫院,https://www.taic.mohw.gov.tw/<br>
衛生福利部臺東醫院,https://www.tait.mohw.gov.tw/<br>
臺南市立醫院,https://www.tmh.org.tw/<br>
衛生福利部臺南醫院,https://www.tnhosp.mohw.gov.tw/<br>
高雄榮民總醫院,https://www.vghks.gov.tw/<br>
臺北榮民總醫院,https://www.vghtpe.gov.tw/<br>
臺北市立萬芳醫院,https://www.wanfang.gov.tw/<br>
國立陽明大學附設醫院,https://www.ymuh.ym.edu.tw/<br>
佑霖診所(原)佑林醫院,https://www.yolinclinic.com.tw/<br>
臺北榮民總醫院員山分院,https://www.ysvh.gov.tw/<br>
育仁醫院,https://yuzenhospital.wixsite.com/yuzenhospital<br>

@endsection
