---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: frontend
  pull: if-not-exists
  image: node:14.2.0
  commands:
  - node -v
  - npm -v
  - npm install
  - npm run prod

- name: backend
  pull: if-not-exists
  image: laradock/workspace:latest-7.4
  commands:
  - php -v
  - composer -V
  - cp .env.example .env
  - composer install --prefer-dist
  - php artisan key:generate
  - php artisan migrate

services:
- name: postgres
  pull: if-not-exists
  image: postgres
  environment:
    POSTGRES_DB: homestead
    POSTGRES_PASSWORD: secret
    POSTGRES_USER: homestead
